Added Asthma Detection ML Model
TAHIR0110/ThereForYou pull request #219
Opened 2024-06-25 19:25 UTC by debangi29

Fixed #200 
Added ML model and python file for Asthma detection

2024-06-30 06:03 UTC, debangi29 commented
Please check thr PR @TAHIR0110 
Thanks :)

2024-06-30 08:31 UTC, Avdhesh-Varshney requested changes
@debangi29 Looks good. You have created a streamlit app. So, attach a working video of this project?

2024-06-30 10:10 UTC, debangi29 commented
I have added the working video file of the detection model

2024-07-01 04:07 UTC, Avdhesh-Varshney requested changes

2024-07-01 04:07 UTC, Avdhesh-Varshney commented on Asthma_Detection/Asthma_Prediction_App.mp4
No, don't commit it in project. Delete it from here and show me in the conversation only.

2024-07-01 06:04 UTC, debangi29 commented
Okay, I have deleted it... 
Heres the video :)

https://github.com/TAHIR0110/ThereForYou/assets/117537653/f954c2b5-070b-41d2-afbc-cbfbf118be80

2024-07-03 04:22 UTC, Avdhesh-Varshney approved these changes

2024-07-03 04:22 UTC, merged