Maternal health risk prediction using machine learning
TAHIR0110/ThereForYou pull request #311
Opened 2024-07-22 17:04 UTC by RajKhanke

work done :
1) models used : Xgboost (applied on final data) ,Gbm , random forest ,Knn
2)data preprocessing ,feature engineering , EDA and analysis
3) Streamlit based web application for taking input and risk prediction

Resolves #262 

Demo :

https://github.com/user-attachments/assets/f20288a9-187c-4fe3-99d5-ee76d981428b

2024-07-22 17:05 UTC, RajKhanke commented
@Avdhesh-Varshney @TAHIR0110 please merge this pr along with level and label of gssoc'24. it will resolve the issue no 262

2024-07-24 04:59 UTC, Avdhesh-Varshney requested changes

2024-07-24 04:59 UTC, Avdhesh-Varshney commented on Maternal health Risk Prediction/webapp.mp4
delete this video

2024-07-24 11:10 UTC, RajKhanke commented
okay

2024-07-24 11:52 UTC, RajKhanke commented
@Avdhesh-Varshney @TAHIR0110 i have completed the required changes  , now please merge this PR along with the level and label of gssoc'24

2024-07-25 07:27 UTC, RajKhanke commented
@TAHIR0110 @Avdhesh-Varshney @Atharv714  ?

2024-07-31 14:15 UTC, RajKhanke commented
@Avdhesh-Varshney ?

2024-08-08 06:09 UTC, TAHIR0110 commented
@RajKhanke kindly delete the demo vid

2024-08-08 06:13 UTC, TAHIR0110 commented
@RajKhanke merged!

2024-08-08 06:13 UTC, merged